from testAngSep import AngSepTestCase
from testS2PtInBox import S2PtInBoxTestCase
from testS2PtInCircle import S2PtInCircleTestCase
from testS2PtInEllipse import S2PtInEllipseTestCase
from testS2CPoly import S2CPolyTestCase
